name: Run SerenityBDD Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '21'

      - name: Cache Gradle dependencies
        uses: actions/cache@v3
        with:
          path: ~/.gradle/caches
          key: gradle-${{ runner.os }}-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: gradle-${{ runner.os }}

      - name: Regenerar el wrapper de Gradle
        run: gradle wrapper

      - name: Dar permisos de ejecución al wrapper de Gradle
        run: chmod +x gradlew

      - name: Limpiar caché de Gradle
        run: rm -rf ~/.gradle/caches

      - name: Run tests with Gradle
        run: ./gradlew clean test aggregate

      - name: Upload Serenity Report
        uses: actions/upload-artifact@v4
        with:
          name: serenity-report
          path: target/site/serenity