name: Run SerenityBDD Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v2
        with:
          distribution: 'temurin'
          java-version: '21'

      - name: Install Chrome
        run: |
          sudo apt-get update
          sudo apt-get install -y google-chrome-stable
      
      - name: Check Chrome version
        run: google-chrome --version

      - name: Verificar directorio actual
        run: |
          echo "Directorio actual: $(pwd)"
          ls -la

      - name: Dar permisos de ejecución al wrapper de Gradle
        run: chmod +x gradlew
        working-directory: ${{ github.workspace }}

      - name: Verificar versión de Java y Gradle
        run: |
          java -version
          ./gradlew --version
        working-directory: ${{ github.workspace }}

      - name: Run tests with Gradle
        run: ./gradlew clean test aggregate --stacktrace
        working-directory: ${{ github.workspace }}

      - name: Upload Serenity Report
        uses: actions/upload-artifact@v4
        with:
          name: serenity-report
          path: target/site/serenity